version: 1
formatters:
    default: 
        format: '%(asctime)s %(name)-11s %(levelname)-8s %(message)s %(pathname)s %(lineno)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
        class: logging.Formatter
    http:
        format: '%(asctime)s %(message)s'
        class: logging.Formatter
filters:
    root_filter:
        class: logging.Filter
        name: root
handlers:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        filename: /var/log/lemon.log
        backupCount: 3
        maxBytes: 524288000
        filters: [root_filter]
    console_handler:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
    access_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: http
        filename: /var/log/lemon-access.log
        backupCount: 5
        maxBytes: 524288000 # 500M
    error_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: http
        filename: /var/log/lemon-error.log
        backupCount: 5
        maxBytes: 524288000 # 500M
loggers:
    console:
        level: DEBUG
        handlers: [console_handler]
        propagate: no
    access:
        level: INFO
        handlers: [access_handler]
        propagate: no
    error:
        level: ERROR
        handlers: [error_handler]
        propagate: no
root:
    level: INFO
    handlers: [file_handler]
#    filters: [root_filter]
