version: 1
formatters:
    default: 
        format: '%(asctime)s %(name)-11s %(levelname)-8s %(message)s %(pathname)s %(lineno)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
        class: logging.Formatter

handlers:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        filename: /var/log/lemon.log
        backupCount: 3
        maxBytes: 1024

    console_handler:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout

loggers:
    console:
        level: DEBUG
        handlers: [console_handler]
        propagate: yes
root:
    level: WARNING
    handlers: [file_handler]
