version: 1
formatters:
    default: 
        format: '%(asctime)s %(name)-11s %(levelname)-8s %(message)s %(pathname)s %(lineno)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
        class: logging.Formatter

handlesr:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        category: ext://logging.LOG_CATEGORY
        maxBytes: 1024

    console_handler:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout

loggers:
    console:
        level: DEBUG
        handlers: [console_handler]
root:
        level: WARNING
        handlers: [file_handler]
